-- MySQL Script generated by MySQL Workbench
-- Fri Sep  2 21:06:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pedras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pedras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedras` DEFAULT CHARACTER SET utf8 ;
USE `pedras` ;

-- -----------------------------------------------------
-- Table `pedras`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(14,2) NOT NULL,
  `informacao` VARCHAR(45) NOT NULL,
  `estoque` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedras`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`imagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NULL,
  `imagem` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Imagens_Produtos`
    FOREIGN KEY (`id_produto`)
    REFERENCES `pedras`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedras`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedras`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Vendas_Adm1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `pedras`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedras`.`produtos_has_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`produtos_has_vendas` (
  `Produtos_idProdutos` INT NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `quantidade` INT NULL,
  `subtotal` DECIMAL(14,2) NULL,
  PRIMARY KEY (`Produtos_idProdutos`, `Pedidos_idPedidos`),
  CONSTRAINT `fk_Produtos_has_Vendas_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `pedras`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Vendas_Vendas1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `pedras`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pedras` ;

-- -----------------------------------------------------
-- Placeholder table for view `pedras`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedras`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `pedras`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedras`.`view1`;
USE `pedras`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
